/* scalar-static-bridge.js
 * Intercepts Scalar backend API calls so they do not 404 in a static export.
 * Auto-generated by the static exporter — do not edit manually.
 */
(function () {
    'use strict';

    function isScalarApiCall(url) {
        if (typeof url !== 'string') return false;
        return url.indexOf('format=json') !== -1 ||
               url.indexOf('format=xml')  !== -1 ||
               url.indexOf('method=book') !== -1 ||
               url.indexOf('method=node') !== -1;
    }

    // --- Override XMLHttpRequest ---
    var OriginalXHR = window.XMLHttpRequest;
    window.XMLHttpRequest_native = OriginalXHR;   // preserve for direct use

    function StaticXHR() {
        this._url    = null;
        this._method = null;
        this._real   = null;
        this.readyState   = 0;
        this.status       = 0;
        this.responseText = '';
        this.response     = '';
        this.onreadystatechange = null;
        this.onload  = null;
        this.onerror = null;
    }

    StaticXHR.prototype.open = function (method, url) {
        this._method = method;
        this._url    = url;
        if (isScalarApiCall(url)) {
            this.readyState = 1;
        } else {
            this._real = new OriginalXHR();
            this._real.open(method, url);
        }
    };

    StaticXHR.prototype.send = function (body) {
        var self = this;
        if (isScalarApiCall(this._url)) {
            // Return an empty Scalar-style response without hitting the network.
            setTimeout(function () {
                self.status       = 200;
                self.responseText = '{}';
                self.response     = '{}';
                self.readyState   = 4;
                if (self.onreadystatechange) self.onreadystatechange();
                if (self.onload) self.onload({ target: self });
            }, 0);
        } else {
            var real = this._real;
            real.onreadystatechange = function () {
                self.readyState   = real.readyState;
                self.status       = real.status;
                self.responseText = real.responseText;
                self.response     = real.response;
                if (self.onreadystatechange) self.onreadystatechange();
                if (real.readyState === 4 && self.onload) {
                    self.onload({ target: self });
                }
            };
            real.send(body);
        }
    };

    StaticXHR.prototype.setRequestHeader = function (h, v) {
        if (this._real) this._real.setRequestHeader(h, v);
    };
    StaticXHR.prototype.getAllResponseHeaders = function () {
        return this._real ? this._real.getAllResponseHeaders() : '';
    };
    StaticXHR.prototype.getResponseHeader = function (h) {
        return this._real ? this._real.getResponseHeader(h) : null;
    };
    StaticXHR.prototype.abort = function () {
        if (this._real) this._real.abort();
    };

    window.XMLHttpRequest = StaticXHR;

    // --- Override fetch() ---
    if (typeof window.fetch === 'function') {
        var originalFetch = window.fetch;
        window.fetch = function (url, options) {
            var urlStr = typeof url === 'string' ? url
                       : (url && typeof url.url === 'string' ? url.url : String(url));
            if (isScalarApiCall(urlStr)) {
                return Promise.resolve(new Response('{}', {
                    status: 200,
                    headers: { 'Content-Type': 'application/json' }
                }));
            }
            return originalFetch.call(window, url, options);
        };
    }

}());
