/* scalar-static-bridge.js
 * Intercepts Scalar backend API calls so they do not 404 in a static export.
 * Auto-generated by the static exporter — do not edit manually.
 */
(function () {
    'use strict';

    // Static asset extensions — requests for these pass through to the real XHR.
    var STATIC_EXTS = {
        css:1, png:1, jpg:1, jpeg:1, gif:1, svg:1,
        woff:1, woff2:1, ttf:1, eot:1, ico:1,
        mp4:1, mp3:1, webm:1, ogg:1, pdf:1, zip:1,
        html:1, htm:1, txt:1, map:1
    };

    // True for any XHR request that should be silently stubbed:
    //   • .js files — already pre-loaded as <script> tags; returning '' lets
    //     jQuery's .done() chain fire without re-eval (avoids duplicate let/const errors)
    //   • Scalar server endpoints (any same-origin URL that isn't a static asset) —
    //     prevents 404s for API endpoints, lenses, editorial workflow, rdf/*, etc.
    function shouldIntercept(url) {
        if (typeof url !== 'string') return false;

        var path = url.split('?')[0].split('#')[0];

        // .js files: always intercept regardless of origin
        if (path.slice(-3) === '.js') return true;

        // For other URLs, only intercept same-origin requests
        try {
            var here   = new URL(window.location.href);
            var there  = new URL(url, window.location.href);
            if (there.host !== here.host) return false;   // cross-origin: pass through
        } catch (e) {
            return false;
        }

        // If it has a known static extension, pass through (real file fetch)
        var ext = path.split('.').pop().toLowerCase();
        if (STATIC_EXTS[ext]) return false;

        // Everything else on the same host is a Scalar server endpoint
        return true;
    }

    // Ask the endpoint handler (installed later in this file, once scalarapi is loaded)
    // whether it can answer this request from the local model. Returns a response body
    // string, or null to fall through to the stubbed 503.
    function staticEndpointAnswer(method, url, body) {
        if (typeof window.__scalarStaticEndpoint !== 'function') return null;
        try {
            return window.__scalarStaticEndpoint(method || 'GET', url, body);
        } catch (e) {
            if (window.console) console.log('static endpoint handler failed for ' + url, e);
            return null;
        }
    }

    // --- Override XMLHttpRequest ---
    var OriginalXHR = window.XMLHttpRequest;
    window.XMLHttpRequest_native = OriginalXHR;   // preserve for direct use

    function StaticXHR() {
        this._url    = null;
        this._method = null;
        this._real   = null;
        this.readyState   = 0;
        this.status       = 0;
        this.responseText = '';
        this.response     = '';
        this.onreadystatechange = null;
        this.onload  = null;
        this.onerror = null;
    }

    StaticXHR.prototype.open = function (method, url) {
        this._method = method;
        this._url    = url;
        if (shouldIntercept(url)) {
            this.readyState = 1;
        } else {
            this._real = new OriginalXHR();
            this._real.open(method, url);
        }
    };

    StaticXHR.prototype.send = function (body) {
        var self = this;
        if (shouldIntercept(this._url)) {
            var path = this._url.split('?')[0].split('#')[0];
            var isJs = path.slice(-3) === '.js';
            // A few endpoints can be answered locally rather than failed — see
            // window.__scalarStaticEndpoint, installed further down this file once
            // scalarapi and the node model are available.
            var answer = staticEndpointAnswer(this._method, this._url, body);
            setTimeout(function () {
                if (answer !== null) {
                    self.status       = 200;
                    self.responseText = answer;
                    self.response     = answer;
                    self.readyState   = 4;
                    if (self.onreadystatechange) self.onreadystatechange();
                    if (self.onload) self.onload({ target: self });
                } else if (isJs) {
                    // .js: return 200 + empty body so jQuery's .done() chain fires
                    // but globalEval('') is a no-op (no duplicate let/const errors).
                    self.status       = 200;
                    self.responseText = '';
                    self.response     = '';
                    self.readyState   = 4;
                    if (self.onreadystatechange) self.onreadystatechange();
                    if (self.onload) self.onload({ target: self });
                } else {
                    // Server endpoint: return 503 so jQuery fires the *error* callback,
                    // not the success callback. Success callbacks expect specific data
                    // shapes (arrays, ontology objects) and crash on '{}'. Error callbacks
                    // in Scalar are universally benign (console.log only).
                    self.status       = 503;
                    self.responseText = '';
                    self.response     = '';
                    self.readyState   = 4;
                    if (self.onreadystatechange) self.onreadystatechange();
                    // Do NOT fire onload for error responses — jQuery uses status to route.
                }
            }, 0);
        } else {
            var real = this._real;
            real.onreadystatechange = function () {
                self.readyState   = real.readyState;
                self.status       = real.status;
                self.responseText = real.responseText;
                self.response     = real.response;
                if (self.onreadystatechange) self.onreadystatechange();
                if (real.readyState === 4 && self.onload) {
                    self.onload({ target: self });
                }
            };
            real.send(body);
        }
    };

    StaticXHR.prototype.setRequestHeader = function (h, v) {
        if (this._real) this._real.setRequestHeader(h, v);
    };
    StaticXHR.prototype.getAllResponseHeaders = function () {
        return this._real ? this._real.getAllResponseHeaders() : '';
    };
    StaticXHR.prototype.getResponseHeader = function (h) {
        return this._real ? this._real.getResponseHeader(h) : null;
    };
    StaticXHR.prototype.abort = function () {
        if (this._real) this._real.abort();
    };

    window.XMLHttpRequest = StaticXHR;

    // --- Override fetch() ---
    if (typeof window.fetch === 'function') {
        var originalFetch = window.fetch;
        window.fetch = function (url, options) {
            var urlStr = typeof url === 'string' ? url
                       : (url && typeof url.url === 'string' ? url.url : String(url));
            if (shouldIntercept(urlStr)) {
                var path = urlStr.split('?')[0].split('#')[0];
                var isJs = path.slice(-3) === '.js';
                var method = (options && options.method) || 'GET';
                var answer = staticEndpointAnswer(method, urlStr, options && options.body);
                if (answer !== null) {
                    return Promise.resolve(new Response(answer, {
                        status: 200,
                        headers: { 'Content-Type': 'application/json' }
                    }));
                }
                // .js: 200 + empty body (no-op globalEval)
                // server endpoints: 503 so callers treat it as an error, not success
                return Promise.resolve(new Response('', {
                    status: isJs ? 200 : 503,
                    headers: { 'Content-Type': 'text/plain' }
                }));
            }
            return originalFetch.call(window, url, options);
        };
    }

}());

// Protect static relative hrefs (../slug/ or ./slug/) from being overwritten
// by scalarpage.makeRelativeLinksAbsolute() at runtime. This guard runs
// synchronously in <head>, before scalarpage.jquery.js initialises, so the
// patched $.fn.attr is already in place when scalarpage tries to rewrite links.
(function ($) {
    if (!$ || !$.fn) return;
    var _attr = $.fn.attr;
    $.fn.attr = function (name, value) {
        if (name === 'href' && typeof value === 'string') {
            this.each(function () {
                var cur = this.getAttribute ? this.getAttribute('href') : null;
                if (cur && (cur.slice(0, 3) === '../' || cur.slice(0, 2) === './')) {
                    return;  // already a correct static-relative path — leave it
                }
                _attr.call($(this), 'href', value);
            });
            return this;
        }
        return _attr.apply(this, arguments);
    };
}(window.jQuery));

// -----------------------------------------------------------------------
// Deferred patches to Scalar's own JS for static-export compatibility.
//
// Each of these needs Scalar's classes (ScalarModel/ScalarNode/ScalarAPI,
// $.scalarpage) to already be defined, but must run before main.js's boot
// logic — registered via $(window).ready(...) in main.js — actually calls
// into them. jQuery fires ready handlers in registration order once the
// whole document has finished parsing, regardless of where in the document
// they were registered; this file loads immediately after jQuery itself
// (the very first script tag after it), so registering our ready handler
// here guarantees it fires before main.js's, while still running only
// after every later <script> tag — including main.js itself — has already
// executed and defined the globals these patches touch.
// -----------------------------------------------------------------------
(function ($) {
    if (!$) return;

    $(document).ready(function () {

        /* Relative path from the current page back to the export root.
         * <link id="approot" href="[asset_root]system/application/"> is present on every
         * page (see page.php); stripping the known suffix recovers asset_root. */
        function exportRoot() {
            var approot = $('link#approot').attr('href') || '';
            return approot.replace(/system\/application\/?$/, '');
        }

        /* getCurrentPageNode() fix.
         *
         * scalarapi looks up document.location.href in nodesByURL, but on a static
         * host that never matches the live Scalar node URLs.
         *
         * Two-part fix:
         * 1. Patch the prototype to look up by the canonical Scalar URL stored in
         *    <link id="current_node"> rather than document.location.href.
         * 2. Pre-seed a minimal ScalarNode so currentNode.current is non-null even if
         *    the RDFa parseNodes() call fails to build the node (e.g. if the CURIE
         *    expansion still has edge cases). parseNodes() will overwrite this with
         *    real data if it succeeds. */
        (function () {
            var linkEl = document.getElementById('current_node');
            if (!linkEl || typeof ScalarModel === 'undefined' || typeof ScalarNode === 'undefined') return;
            var canonicalUrl = linkEl.getAttribute('href');

            ScalarModel.prototype.getCurrentPageNode = function () {
                return this.nodesByURL[canonicalUrl] ||
                       this.nodesByURL[unescape(canonicalUrl)] ||
                       undefined;
            };

            if (!scalarapi.model.nodesByURL[canonicalUrl]) {
                // hasVersion has to be here as well as in the versionData below: anything that
                // later rebuilds an RDF-JSON entry from this node reads its version list back
                // out of this object, and an entry without it makes parseNodes() throw the
                // node's real version away for an empty placeholder.
                var minJson = {
                    'http://www.w3.org/1999/02/22-rdf-syntax-ns#type': [
                        { value: 'http://scalar.usc.edu/2012/01/scalar-ns#Composite', type: 'uri' }
                    ],
                    'http://purl.org/dc/terms/hasVersion': [
                        { value: canonicalUrl + '.1', type: 'uri' }
                    ]
                };
                var node = new ScalarNode(canonicalUrl, minJson,
                    [{ url: canonicalUrl + '.1', json: {} }]);
                scalarapi.model.addNode(node);
            }
        }());

        /* loadNode()/loadPage() fix.
         *
         * Callers throughout Scalar's JS (most importantly jquery.mediaelement.js's
         * loadMetadata(), which every media element goes through) call this with
         * forceReload hardcoded true, so the original implementation always issues an
         * AJAX request and only calls the success callback once that resolves. Two
         * problems in a static export: there's no live server to answer it, and the
         * request uses dataType:"jsonp" — a dynamically injected <script> tag, not an
         * XHR/fetch call — so this file's XHR/fetch overrides (above) can't even
         * intercept it. Every call would previously hang forever and the media
         * element would never finish initializing.
         *
         * Every node in the book is already embedded as RDFa on every rendered page
         * (see static_export/page.php's "other content nodes" block) and parsed into
         * scalarapi.model.nodesByURL by main.js at boot — so the data is always already
         * in hand and nothing has to be fetched.
         *
         * What this must NOT do is hand that data back synchronously. Two call styles
         * share this one method:
         *
         *     if (scalarapi.loadNode(slug, true, cb, …) == 'loaded') cb();   // idiom A
         *     scalarapi.loadNode(slug, true, cb, …);                         // idiom B
         *
         * Returning 'loaded' without firing the callback serves A and silently strands
         * every B caller (page notes, annotated media, the TOC submenus). Returning
         * 'loaded' *and* firing it runs A's callback twice. Firing asynchronously and
         * returning 'loading' — the live method's return on the branch that issues a
         * request — is the one combination that serves both, and it also restores the
         * asynchrony every caller was written against.
         *
         * That asynchrony is load-bearing, not just tidy. $.fn.mediaelement stores the
         * MediaElement on the link *after* `new MediaElement(...)` returns, but the
         * constructor calls loadMetadata() as its last act. Resolving synchronously
         * therefore ran the whole metadata chain — including the 'mediaElementMetadataHandled'
         * and 'mediaElementMediaLoaded' events — while link.data('mediaelement') was still
         * undefined, so every handler that reads it back (scalarmediadetails' citations
         * panel, scalarpage's media layout) threw. That is what broke the Citations tab.
         *
         * The callback is handed an object in the same shape as the live API's RDF-JSON
         * response — the node entry keyed by node URL, plus one entry per version keyed
         * by version URL — because callers index into it that way (see the widget branch
         * of scalarpage.jquery.js, which walks node[uri]['dcterms:hasVersion'] to reach
         * the version's sioc:content).
         *
         * scalar:citation is grafted on for the same reason loadNodesByType() below does it:
         * the live API attaches it to every returned node to carry pagination state, and the
         * visualizations read 'methodNumNodes' off the response to decide whether to ask for
         * another page. A single node is always the whole result, so the count is 1 — which,
         * being under the visualizations' page size, reads as "last page" and stops the walk.
         * Without it they would re-request the same node forever. */
        var NODE_CITATION = [{
            value: 'method=node;methodNumNodes=1;',
            type:  'literal'
        }];

        /* One or more nodes rendered as the live API's RDF-JSON: the node entry keyed by node
         * URL, plus one entry per version keyed by version URL. The version entries are not
         * optional — ScalarModel.parseNodes() follows dcterms:hasVersion into the same payload
         * and builds a ScalarVersion from whatever it finds there, so omitting them replaces a
         * node's real versions with a broken one and takes node.current with it. */
        function nodeEntries(nodes, into) {
            var data = into || {};
            for (var k = 0; k < nodes.length; k++) {
                var node = nodes[k];
                if (node == null) continue;
                // Copy rather than annotate node.data in place: that object is the RDFa
                // dump entry the node was parsed from, and citation is per-query state.
                var entry = {};
                for (var prop in node.data) entry[prop] = node.data[prop];
                entry['http://scalar.usc.edu/2012/01/scalar-ns#citation'] = NODE_CITATION;

                data[node.url] = entry;
                for (var i = 0; i < node.versions.length; i++) {
                    data[node.versions[i].url] = node.versions[i].data.json;
                }
            }
            return data;
        }

        function nodeResponse(node) { return nodeEntries([node]); }

        if (typeof ScalarAPI !== 'undefined') {

            ScalarAPI.prototype.loadNode = ScalarAPI.prototype.loadPage =
                function (uriSegment, forceReload, successCallback) {

                // getNode() rather than a raw nodesByURL lookup: callers pass a slug in
                // most places but a full node URL in some (scalarmedia's related-media
                // walk hands it a dcterms:relation value verbatim).
                var node = this.getNode(uriSegment);
                if (node == null) return 'loading';

                if (typeof successCallback === 'function') {
                    var data = nodeResponse(node);
                    window.setTimeout(function () { successCallback(data); }, 0);
                }

                return 'loading';
            };

            /* loadCurrentPage()/loadCurrentNode() fix — the visualizations.
             *
             * Same jsonp dead end as loadNode() above, and the same fix, but it needed its own
             * patch: it takes no slug (it derives one from document.location) and keeps its own
             * loading-status queue, so it is a separate method rather than a wrapper.
             *
             * scalarvisualizations.jquery.js is the only exported caller, and it walks a fixed
             * load sequence — book, current page, current page's connections, paths, tags,
             * media, pages, annotations, comments — advancing one step per callback. Steps two
             * and three are this method. It always took the request branch here (the branch is
             * gated on model.currentPageNode, which is null in an export for the reason below),
             * the jsonp <script> 404'd, base.parseData never ran, and the sequence stopped dead
             * at step two: every visualization sat on its loading bar having drawn nothing.
             *
             * Step one, loadBook(), needs no patch — it returns 'loaded' straight from the model
             * because getBookNode() finds the scalar:Book node page.php emits on every page, and
             * the caller runs its own callback on that.
             *
             * model.currentPageNode is assigned here because nothing else in an export ever
             * assigns it: ScalarModel.addNode() sets it only for the node whose URL matches
             * document.location, which is exactly the comparison that fails once the book is
             * served from somewhere other than the Scalar server it was written on (hence the
             * getCurrentPageNode() patch above). parseCurrentPage() would have cached it on the
             * live API's success path, so setting it keeps that side effect intact. */
            ScalarAPI.prototype.loadCurrentNode = ScalarAPI.prototype.loadCurrentPage =
                function (forceReload, successCallback) {

                var node = this.model.getCurrentPageNode();
                if (node == null) return 'loading';

                this.model.currentPageNode = node;

                if (typeof successCallback === 'function') {
                    var data = nodeResponse(node);
                    window.setTimeout(function () { successCallback(data); }, 0);
                }

                return 'loading';
            };
        }

        /* loadNodesByType()/loadPagesByType() fix — the Index modal, and the lens/grid
         * visualizations, which are the only exported callers.
         *
         * Both go through this one method, which fires
         * $.ajax({url: 'rdf/instancesof/<type>', dataType: 'jsonp'}) and does nothing until
         * that resolves. dataType 'jsonp' means a dynamically injected <script> tag, not an
         * XHR or fetch call, so the overrides at the top of this file cannot intercept it:
         * the request simply 404s, the success callback never fires, and the caller waits
         * forever. That is why the Index modal sat on "Loading..." — nothing ever called
         * ScalarIndex.handleResults() to hide the spinner and fill the table.
         *
         * Everything the method needs is already local. getNodesWithProperty() reads straight
         * out of scalarapi.model, which main.js populates at boot from the RDFa every exported
         * page carries (see static_export/page.php — every node in the book, plus the
         * oac:Annotation relations that give path/tag/annotation nodes those scalarTypes in
         * the first place). So this resolves from the model and hands the callback the same
         * shape the API would have: an object keyed by node URL.
         *
         * The one piece of the response that isn't node data is scalar:citation. The live API
         * grafts it onto every returned node (see _pagination_by_ref() in RDF_Object.php) to
         * carry pagination state in its 'methodNumNodes' field, and both callers depend on it:
         * ScalarIndex reads it off the *node* to size its pager, the visualizations read it off
         * the *response* to decide when they've reached the last page. Hence both below.
         *
         * Note methodNumNodes counts the nodes remaining from `start` onward, NOT the size of
         * the whole collection — _index_by_ref() decrements $settings['total'] once for each
         * row it pages past. ScalarIndex's maxPages arithmetic reads it as a total, which is
         * only correct because setDisplayMode() resets currentPage to 1 whenever it resets
         * maxPages to 0, so the figure it latches is always the one from a start=0 call.
         *
         * Ordering is alphabetical rather than the live API's (which varies by model, since
         * each content type is fetched through its own). The Index offers no sort control, so
         * any order is as faithful as another; alphabetical is the one that makes an A–Z
         * listing browsable, and re-deriving it from the model on each call keeps pagination
         * consistent across requests. */
        if (typeof ScalarAPI !== 'undefined') {

            var CITATION = 'http://scalar.usc.edu/2012/01/scalar-ns#citation';

            ScalarAPI.prototype.loadNodesByType = ScalarAPI.prototype.loadPagesByType =
                function (type, forceReload, successCallback, errorCallback,
                          depth, references, relation, start, results) {

                var nodes = this.model.getNodesWithProperty('scalarType', type, 'alphabetical');
                var from  = (start   == null) ? 0            : parseInt(start, 10);
                var count = (results == null) ? nodes.length : parseInt(results, 10);

                var citation = [{
                    value: 'method=instancesof;methodNumNodes=' + Math.max(0, nodes.length - from) + ';',
                    type:  'literal'
                }];

                var data = {};
                var page = nodes.slice(from, from + count);

                for (var i = 0; i < page.length; i++) {
                    var node  = page[i];
                    // Copy rather than annotate node.data in place: that object is the RDFa
                    // dump entry the node was parsed from, and citation is per-query state.
                    var entry = {};
                    for (var prop in node.data) entry[prop] = node.data[prop];
                    entry[CITATION] = citation;
                    node.properties[CITATION] = citation;
                    data[node.url] = entry;
                }

                if (typeof successCallback === 'function') {
                    // Async, like the $.ajax call this replaces: callers show a spinner and
                    // then keep working on the assumption the callback lands after they return.
                    window.setTimeout(function () { successCallback(data); }, 0);
                }

                // 'loading', matching the live method's return on the branch that issues a
                // request. Not 'loaded' — the visualizations respond to that by calling
                // parseData() themselves, which would double up with the callback above.
                return 'loading';
            };
        }

        /* Page footer ("colophon") fix.
         *
         * page.addColophon() (scalarpage.jquery.js) builds three links from data that
         * doesn't exist in this export: a permalink to this exact version, a link to
         * the version-history browser, and a link to a live-only ".meta" URL extension
         * that renders the metadata table server-side. None of that is exported (see
         * CLAUDE.md — version history is dropped), so:
         *   - the version permalink becomes plain text (this export only ever has the
         *     one version)
         *   - "All versions" is dropped outright (no version history is exported)
         *   - "Metadata" is repointed at <slug>.meta/, a page static_export_model.php
         *     writes alongside every <slug>/index.html (see _write_meta_page()) — a real
         *     local page instead of a JS-only view
         *   - "Scalar Feedback" (a contact link to the Scalar project itself, not this
         *     book) is dropped — it's not meaningful once the site is exported
         *
         * addColophon() is NOT a hook we can pre-empt: it runs synchronously as part of
         * $.scalarpage()'s own constructor body (a giant switch(viewType) block, not a
         * separate .init() called after construction), so by the time $.scalarpage(e,
         * options) returns, the footer this fixes has already been built — wrapping the
         * *returned* object's addColophon (as an earlier version of this patch did) never
         * fires, because addColophon is never called again after that first, internal
         * call. So this runs the fixup directly on the already-built DOM right after
         * $.scalarpage() returns, instead of trying to intercept the call that built it. */
        if (typeof $.scalarpage === 'function') {
            var _originalScalarpage = $.scalarpage;
            $.scalarpage = function (e, options) {
                var page = _originalScalarpage(e, options);   // addColophon has already run by here

                var $par = $('#footer #scalar-credit');

                var versionLink = $par.find('a[title="Go to permalink"]')[0];
                if (versionLink) {
                    $(versionLink).replaceWith(versionLink.textContent);
                }

                var allVersionsLink = $par.find('a[title="View all versions"]')[0];
                if (allVersionsLink) {
                    var trailingSep = allVersionsLink.nextSibling;
                    if (trailingSep && trailingSep.nodeType === 3 && /^\s*\|\s*$/.test(trailingSep.nodeValue)) {
                        trailingSep.parentNode.removeChild(trailingSep);
                    }
                    allVersionsLink.parentNode.removeChild(allVersionsLink);
                }

                var metaLink = $par.find('a[title="View metadata for this page"]')[0];
                if (metaLink) {
                    var currentSlug = scalarapi.model.getCurrentPageNode().slug;
                    $(metaLink).attr('href', exportRoot() + currentSlug + '.meta/');
                }

                var feedbackLink = $par.find('a[href="http://scalar.usc.edu/contact/"]')[0];
                if (feedbackLink) {
                    // Unlike the " | " before "All versions" (its own standalone text node),
                    // this pipe is the tail of the same text node as ") " from the "Powered by
                    // Scalar (version)" segment when neither Terms of Service nor Privacy
                    // Policy links are present (as here — see page.php, neither is emitted) —
                    // so trim just the trailing "|", not the whole node.
                    var feedbackSep = feedbackLink.previousSibling;
                    if (feedbackSep && feedbackSep.nodeType === 3) {
                        feedbackSep.nodeValue = feedbackSep.nodeValue.replace(/\|\s*$/, '');
                    }
                    feedbackLink.parentNode.removeChild(feedbackLink);
                }

                /* Now that page.php emits the book's path/tag/annotation relations (see its
                 * "Relationships" block), scalarpage builds the navigation that hangs off
                 * them: path breadcrumbs, prev/next arrows, "Continue to..." buttons, the
                 * "Step N of the ... path" citation lines, and the tag/path relationship
                 * lists at the foot of the page. Every one of those hrefs is
                 * ScalarNode.url — the live Scalar address — sometimes with a "?path=<slug>"
                 * suffix carrying which path the reader is travelling. staticHref() keeps
                 * that suffix and replaces only the book-URL half, so path state survives
                 * the rewrite.
                 *
                 * This has to run *after* _originalScalarpage() rather than before: parts of
                 * addRelationshipNavigation() build their final href by reading an existing
                 * one back out and appending "?path=...", and the $.fn.attr guard at the top
                 * of this file deliberately refuses to overwrite an href that already looks
                 * static — so rewriting first would make those appends silently no-op. */
                rewriteNodeLinks(document.body);

                return page;
            };
        }

        /* Node URL -> export path.
         *
         * Every link Scalar's JS builds for a page comes from ScalarNode.url, the
         * canonical live Scalar URL. That URL has to stay absolute in the model — it
         * doubles as the node's RDF identifier, and nodesByURL is keyed on it — so the
         * links are rewritten after the fact, wherever they land in the DOM.
         *
         * slugTarget() mirrors _slug_target() in static_export_model.php: pages live at
         * <slug>/, except the home page, which is written to the export root as
         * index.html with no directory of its own. Naming the file explicitly (rather
         * than linking the bare directory) keeps the link working over file://, where
         * no server supplies a directory index. */
        function slugTarget(slug) {
            return (slug === '' || slug === 'index') ? 'index.html' : slug + '/';
        }

        var bookUrl = scalarapi.model.urlPrefix || $('link#parent').attr('href') || '';

        function staticHref(href) {
            if (typeof href !== 'string' || bookUrl === '') return null;
            if (href.indexOf(bookUrl) !== 0) return null;      // external or already relative

            // Preserve any ?path=/&m= state or #anchor the caller appended.
            var after = href.slice(bookUrl.length);
            var cut   = after.search(/[?#]/);
            var slug  = (cut === -1 ? after : after.slice(0, cut)).replace(/^\/+|\/+$/g, '');
            var rest  = cut === -1 ? '' : after.slice(cut);

            return exportRoot() + slugTarget(slug) + rest;
        }

        /* Rewrite in place every node link at or under the given scope. Skips .metadata
         * links: those are page.php's inert RDFa, where the absolute URL is the point.
         * addBack() so a scope that is itself an <a> — what the observer below hands it
         * when a single link is inserted — is rewritten too, not just its descendants.
         *
         * A link whose visible text *is* the URL it points at gets its label moved as well,
         * or it goes on advertising the original site while quietly linking somewhere else.
         * Two rows are built that way: "Scalar URL" in the metadata table (main.js's
         * addMetadataTableForNodeToElement) and "rdf:resource" on the .meta pages
         * (_build_meta_page_body in static_export_model.php). The label becomes the resolved
         * absolute address — read back off the element, which is what the browser itself
         * would resolve the new relative href to — rather than the relative href, because
         * the point of that row is to give the reader an address they can copy.
         *
         * Deliberately narrow: it fires only when the text matches the href exactly, so the
         * neighbouring "Source URL" row, linkified dcterms:source values, and every ordinary
         * titled link are left alone. */
        function rewriteNodeLinks(scope) {
            $(scope).find('a[href]').addBack('a[href]').not('.metadata').each(function () {
                var original = this.getAttribute('href');
                var href     = staticHref(original);
                if (href === null) return;

                var labelsItsOwnHref = $(this).text().trim() === original.trim();
                this.setAttribute('href', href);
                if (labelsItsOwnHref && typeof this.href === 'string') $(this).text(this.href);
            });
        }

        /* Catch-all rewrite for links Scalar's JS builds after the page has been laid out.
         *
         * The explicit rewriteNodeLinks() calls further down cover the DOM as it stands
         * when $.scalarpage() and $.fn.scalarheader() return, but a lot of node links are
         * built later and on demand, from ScalarNode.url like all the rest:
         *
         *   - the media info tabs (scalarmedia.jquery.js) — an annotation's title link and
         *     its tag buttons, the Related pane's node links, and the "Scalar URL" row of
         *     the Details tab; the annotation bodies in particular are only built when the
         *     reader clicks an annotation, long after any one-shot pass has run
         *   - the Citations dialog (scalarmediadetails.jquery.js) — "View media page", the
         *     citing-page attributions, the "Step N of the … path" lines, and tag links
         *   - the Table of Contents slide-out panels, the visualizations' inspector, and
         *     the structured gallery
         *
         * There is no single hook to wrap for those: $.scalarmedia returns nothing, and the
         * builders are closures inside it. Watching the document instead catches all of them
         * — and anything added later by code this file doesn't know about — with one rule.
         *
         * Only childList mutations are observed, so setting an href here cannot re-trigger
         * the observer. Observer callbacks are delivered at the microtask checkpoint after
         * the script that inserted the nodes has finished, which keeps this clear of the
         * ordering hazard the $.scalarpage() rewrite below documents: builders that append a
         * link and then read its href back to tack on "?path=…" always do both within one
         * synchronous block, so the rewrite lands after the read, not between them. */
        if (window.MutationObserver) {
            new MutationObserver(function (records) {
                for (var i = 0; i < records.length; i++) {
                    var added = records[i].addedNodes;
                    for (var j = 0; j < added.length; j++) {
                        if (added[j].nodeType === 1) rewriteNodeLinks(added[j]);
                    }
                }
            }).observe(document.documentElement, { childList: true, subtree: true });
        }

        /* addTemplateToURL() fix.
         *
         * Not every node link Scalar builds is an href for rewriteNodeLinks() to find.
         * The Index modal's result rows navigate from a click handler instead —
         *
         *     row.on('click', function () {
         *         document.location = addTemplateToURL($(this).data('node').url, 'cantaloupe');
         *     })
         *
         * (scalarindex.jquery.js) — with the row's visible <a> left as href="javascript:;",
         * so there is no href in the DOM at all and every row in the Index sent the reader
         * back to the live book. scalarstructuredgallery.jquery.js builds its block headings
         * through the same call.
         *
         * addTemplateToURL() is the common funnel: main.js defines it globally to append
         * ?template=cantaloupe to any URL belonging to this book. Overriding it reroutes
         * those destinations through staticHref(), and drops the ?template= var along the
         * way — it selects a server-side melon, which means nothing in an export. URLs it
         * doesn't recognise as this book's (the login, register and dashboard links in the
         * user menu) pass through untouched, exactly as the original does.
         *
         * Callers that append their own query string to the result — the structured
         * gallery's addTemplateToURL(node.url, …) + '?path=' + slug — still compose
         * correctly, because staticHref() returns a bare '<root><slug>/' with no query of
         * its own unless the URL it was handed already carried one.
         *
         * main.js declares addTemplateToURL as a hoisted `function` statement, so this
         * assignment has to land after main.js has run. It does: the whole block is a
         * $(document).ready handler, and every <script> tag on the page — main.js included
         * — has finished executing before the first ready handler fires. */
        if (typeof window.addTemplateToURL === 'function') {
            window.addTemplateToURL = function (url, templateName) {
                if (typeof url !== 'string') return url;
                var href = staticHref(url);
                return (href !== null) ? href : url;
            };
        }

        /* Metadata table "View as" row fix.
         *
         * addMetadataTableForNodeToElement() (main.js) builds the table behind the media
         * Details tab, the Citations dialog's Details section and the visualizations'
         * inspector. Its first row, "Scalar URL", and any node links in the rows below are
         * ordinary hrefs the observer above repoints at this export, label included — see
         * rewriteNodeLinks().
         *
         * Its last row is the exception. "View as: RDF-XML, RDF-JSON, HTML" links to three
         * live-only URL extensions on the node; none of them is a page, so the observer would
         * dutifully rewrite them into three directories that don't exist. Two are dropped
         * (no RDF is exported) and the third is repointed at <slug>.meta/, the real page
         * static_export_model.php writes for every item — the same substitution the colophon
         * fix above makes for its "Metadata" link.
         *
         * Wrapping rather than replacing via main.js's customAddMetadataTableForNodeToElement
         * hook: the table is a long list of predicate rows that only needs this one edit, and
         * a wrapper can't drift out of sync with it the way a reimplementation would.
         *
         * The row is found by its label rather than by position because a node with no
         * auxProperties puts it at a different index than one with several. */
        if (typeof window.addMetadataTableForNodeToElement === 'function') {
            var _originalMetadataTable = window.addMetadataTableForNodeToElement;
            window.addMetadataTableForNodeToElement = function (node, element) {
                _originalMetadataTable(node, element);
                $(element).find('table').last().find('tr').each(function () {
                    var cells = $(this).children('td');
                    if (cells.eq(0).text() !== 'View as') return;
                    if (!node.slug) { $(this).remove(); return; }
                    cells.eq(1).empty().append(
                        $('<a>HTML</a>').attr('href', exportRoot() + node.slug + '.meta/'));
                });
            };
        }

        /* Media source paths.
         *
         * Bundled media is referenced relative to the page it appears on — page.php emits
         * art:url as '<asset_root>media/<file>' — so that the export works from any
         * directory, any host, or from disk over file://.
         *
         * jQuery.MediaElementModel.init() then resolves that value the one way a live Scalar
         * never has to think about:
         *
         *     this.path = (this.path.indexOf('://') == -1)
         *         ? scalarapi.model.urlPrefix + this.path : this.path;
         *
         * On the live site a media path is either storage-relative to the book root or
         * already absolute, so prefixing the book URL is right. Here it turns
         * '../media/x.jpg' into '<original book URL>/../media/x.jpg' — a request aimed at
         * the site the export was taken from, for a file that isn't there. Every self-hosted
         * image, video and audio file fails this way; third-party media is unaffected because
         * it already carries a scheme.
         *
         * The fix belongs on ScalarVersion.sourceFile rather than on the links or on
         * model.path, because sourceFile is what actually reaches the player:
         * MediaElementController.handleMetadata() overwrites model.path with
         * node.current.sourceFile before handing off to the view, so anything corrected
         * earlier in the chain is thrown away a moment later. It is also the value
         * scalarpage.jquery.js writes into media links and then compares those links back
         * against when it re-lays out a page (see the "inline media (subsequent, after page
         * resize)" branch) — so moving both sides at once, by changing sourceFile itself,
         * keeps those comparisons matching, which rewriting the hrefs alone would not.
         *
         * Unlike the per-instance prototypes inside jquery.mediaelement.js, this one is
         * declared once at the top level of scalarapi.js, so a single wrapper holds. The
         * space/'#' escaping mirrors what parseData() itself applies to sourceFile, done
         * before resolution so a '#' in a filename can't be read as a fragment. */
        /* Resolve one of those page-relative media paths to an absolute URL, the way the
         * browser would resolve the same value in an href. Returns the value untouched if it
         * already carries a scheme, is a bare fragment, or won't parse. The space/'#'
         * escaping mirrors what scalarapi applies to sourceFile itself, done before
         * resolution so a '#' in a filename can't be read as a fragment. */
        function resolveAgainstPage(value) {
            if (typeof value !== 'string' || value === '') return value;
            if (value.charAt(0) === '#') return value;
            if (/^[a-z][a-z0-9+.-]*:/i.test(value)) return value;
            try {
                return new URL(value.replace(/ /g, '%20').replace(/#/g, '%23'),
                               document.baseURI).href;
            } catch (e) {
                return value;   // unparseable — leave it for Scalar to handle
            }
        }

        if (typeof ScalarVersion !== 'undefined') {
            var _originalVersionParseData = ScalarVersion.prototype.parseData;
            ScalarVersion.prototype.parseData = function (data, node) {
                _originalVersionParseData.call(this, data, node);
                this.sourceFile = resolveAgainstPage(this.sourceFile);
            };
        }

        /* Thumbnails take the same wrong turn, one method further along.
         *
         * page.php emits art:thumbnail as a path relative to the page (see $emit_node_rdfa),
         * for the same portability reason art:url is relative. ScalarNode keeps that value
         * verbatim, and getAbsoluteThumbnailURL() — which the Index modal, the structured
         * gallery, path-navigation previews and video poster frames all call — makes it
         * absolute the only way a live Scalar ever needs to:
         *
         *     if (url.indexOf('://') == -1) url = scalarapi.model.urlPrefix + url;
         *
         * which aims the request at the site the export was taken from. Resolving against the
         * page instead gives the bundled copy. Third-party thumbnails already carry a scheme
         * and are returned untouched, exactly as before.
         *
         * Wrapping the accessor rather than the parse step, because it is the single funnel
         * every consumer goes through, and because leaving node.thumbnail as the raw relative
         * value keeps the truthiness checks those consumers guard with ('if (node.thumbnail)')
         * reading the same as they do on a live server. */
        if (typeof ScalarNode !== 'undefined') {
            var _originalAbsoluteThumbnailURL = ScalarNode.prototype.getAbsoluteThumbnailURL;
            ScalarNode.prototype.getAbsoluteThumbnailURL = function () {
                var url = _originalAbsoluteThumbnailURL.apply(this, arguments);
                return (url === null) ? null : resolveAgainstPage(this.thumbnail);
            };
        }

        /* Banners take the same turn again, and this one has no accessor to wrap.
         *
         * page.php emits scalar:banner as a page-relative path (see $emit_node_rdfa), and the
         * 'splash', 'book_splash' and 'image_header' layouts in scalarpage.jquery.js read
         * ScalarNode.banner and resolve it inline:
         *
         *     if (banner.length && -1 == banner.indexOf('//')) {
         *         banner = $('link#parent').attr('href') + banner;
         *     }
         *
         * That runs inside $.scalarpage()'s constructor body, so there is nothing to intercept
         * between the read and the use — the value itself has to already be absolute by the
         * time the node is built. Hence parseData rather than an accessor, matching how
         * sourceFile is handled above. Once it is absolute the '//' test fails and the layout
         * uses it as-is.
         *
         * A useful side effect: page.getMetadataForMediaUrl(), which those layouts call next to
         * fetch the banner's title and alt text, only issues a request when the URL sits under
         * <link id="parent"> — the original book's address. An absolute export URL doesn't, so
         * it takes the "external file" branch and makes no request, instead of firing a
         * cross-origin call at the site the export came from. The trade is that a bundled
         * banner gets no "Background: <title>" credit line under it, exactly as a third-party
         * banner gets none on a live server.
         *
         * thumbnail is deliberately left alone here — it is read through
         * getAbsoluteThumbnailURL() (patched above), and consumers guard on the raw value with
         * 'if (node.thumbnail)', which should read the same as it does on a live server. */
        if (typeof ScalarNode !== 'undefined') {
            var _originalNodeParseData = ScalarNode.prototype.parseData;
            ScalarNode.prototype.parseData = function (json, versionData) {
                _originalNodeParseData.call(this, json, versionData);

                /* ScalarNode.data is assigned once, in the constructor, and never refreshed —
                 * parseData() updates .properties, .versions and the mapped fields but leaves
                 * .data holding whatever the node was first built from. Normally invisible,
                 * because a node is usually built from the data it keeps. Not here: the
                 * getCurrentPageNode() fix above pre-seeds the current page's node with a
                 * minimal {rdf:type} stub before main.js has parsed the page's RDFa, so from
                 * then on .data is that stub even though the node itself is fully populated.
                 *
                 * That matters because .data is what an RDF-JSON response gets rebuilt from
                 * (nodeEntries() above, and loadNodesByType()'s entries). Handing parseNodes()
                 * a stub with no dcterms:hasVersion made it replace the node's real version
                 * with an empty '.0' placeholder — so the current page, alone among the nodes
                 * in the book, lost its title the moment any of those ran: "(No title)" in the
                 * Index, in the visualizations, and in the Table of Contents.
                 *
                 * Keeping .data in step with the last parse is also what the two accessors that
                 * read it — getReferences() and getOwner() — have always assumed. */
                this.data = json;

                this.banner = resolveAgainstPage(this.banner);
            };
        }

        /* Citations tab double-open fix.
         *
         * scalarmedia.jquery.js builds each media tab as an <input type="radio"> plus its
         * <label>, keeps both in one jQuery set, and binds the tab's behaviour to the set:
         *
         *     var detailsTab = $('<input … id="detailsTab"><label for="detailsTab">Citations</label>')
         *     detailsTab.on('click', function () { media.options['details'].show(node, …) })
         *
         * Clicking the label fires that handler once for the label, and again for the click
         * the browser forwards to the radio it labels — so the handler runs twice per click.
         * For every other tab that is harmless, because they all call showTab(), which is
         * idempotent. The Citations tab is the exception: showMedia() appends a fresh
         * .manual_slideshow to the dialog every time and only ever clears it from hide(), so
         * the second call lays a second copy of the panel over the first. .manual_slideshow
         * is `position:absolute; top:0; width:100%; height:100%`, so that second copy covers
         * the one the reader is looking at and swallows every click aimed at it — the panel
         * renders correctly and then responds to nothing.
         *
         * Dropping the label's copy of the handler leaves the radio's, which the label still
         * activates on click and which keyboard activation fires too, so nothing is lost.
         *
         * This is a bug in Scalar's own JS, not something the export introduces — the same
         * double-fire happens on a live server. What the export changes is only how it
         * presents: the loadNode() patch above resolves metadata on a timer rather than over
         * the network, fast enough that the callback can land between the two clicks, which
         * lets the second call rebuild the sidebar as well as the slideshow. Fixing it here
         * rather than in scalarmedia.jquery.js keeps the live site's behaviour untouched. */
        if (typeof $.scalarmedia === 'function') {
            var _originalScalarmedia = $.scalarmedia;
            $.scalarmedia = function (m, e, options) {
                var result = _originalScalarmedia.apply(this, arguments);
                $(e).find('.media_tabs label[for="detailsTab"]').off('click');
                return result;
            };
        }

        /* getFileExtension() vs. the home page's filename.
         *
         * scalarpage.addMediaElements() reads a URL extension off the current address and
         * routes on it — 'edit', 'meta', 'annotation_editor', each with its own branch, and
         * '' for an ordinary page. Only that last branch builds media: it is where inline
         * media links become players, where the media info tabs (Description / Details /
         * Citations / Source file) are attached, and where page.mediaDetails — the Citations
         * dialog itself — is constructed.
         *
         * On a live Scalar every page address is extensionless, so '' is the normal case.
         * The export's home page is not: it is written to the root as index.html, and linked
         * that way on purpose, so the link still resolves when the export is opened from disk
         * over file:// where no server supplies a directory index (see _slug_target() in
         * static_export_model.php and slugTarget() above). getFileExtension() reads that
         * filename and reports 'html', no branch matches, and the home page silently ends up
         * with no media at all — no players, no tabs, no dialog. The same applies to any page
         * reached as <slug>/index.html rather than <slug>/.
         *
         * Special-casing that one filename is narrow enough to be safe: the method is also
         * used to sniff real media files (jquery.mediaelement.js's format detection,
         * scalarmedia's .vtt check), and none of those is ever named index.html. */
        if (typeof ScalarAPI !== 'undefined') {
            var _originalGetFileExtension = ScalarAPI.prototype.getFileExtension;
            ScalarAPI.prototype.getFileExtension = function (uri) {
                if (typeof uri === 'string' &&
                    uri.split('?')[0].split('#')[0].slice(-11) === '/index.html') return '';
                return _originalGetFileExtension.apply(this, arguments);
            };
        }

        /* ------------------------------------------------------------------
         * Locally answered API endpoints.
         *
         * Everything else same-origin is stubbed with a 503 (see the top of this file), which
         * is right for endpoints whose absence is harmless. These three are not harmless — the
         * first starves every lens-driven visualization of its data — so they are answered from
         * the model instead. The transport layer calls this through window.__scalarStaticEndpoint;
         * returning null falls through to the 503.
         * ------------------------------------------------------------------ */

        /* Which nodes a lens content-selector picks out. Mirrors
         * Lens_model::get_pages_from_content_selector() — including its ordering, where an
         * 'items' array wins over the selector's declared type. Returns null for a selector
         * this doesn't implement, which aborts the whole resolution rather than silently
         * returning a wrong (usually much larger) set. */
        function lensSelectNodes(selector) {
            if (!selector) return null;

            var model = scalarapi.model, i, nodes = [];

            // specific-items: an explicit list of slugs.
            if (selector.items && selector.items.length) {
                for (i = 0; i < selector.items.length; i++) {
                    var node = scalarapi.getNode(selector.items[i]);
                    if (node != null) nodes.push(node);
                }
                return nodes;
            }

            if (selector.type !== 'items-by-type') return null;

            switch (selector['content-type']) {

                // The book's table of contents: the scalar:Page node at <book_url>toc, whose
                // dcterms:references list page.php emits on every exported page.
                case 'table-of-contents':
                    var toc = model.nodesByURL[model.urlPrefix + 'toc'];
                    return toc ? toc.getRelatedNodes('reference', 'outgoing') : [];

                // Every content row in the book — composites and media, which is what the
                // server's unfiltered pages->get_all() returns.
                case 'all-content':
                case 'content':
                    return model.getNodesWithProperty('scalarType', 'page')
                        .concat(model.getNodesWithProperty('scalarType', 'media'));

                case 'page':
                case 'composite':
                    return model.getNodesWithProperty('scalarType', 'page');

                case 'file':
                case 'media':
                    return model.getNodesWithProperty('scalarType', 'media');

                // The relational types. A node carries one of these scalarTypes precisely when
                // it has relations of that kind, which is the same test the server makes by
                // asking whether get_children() returns anything.
                case 'path':
                case 'tag':
                case 'annotation':
                case 'reply':
                case 'comment':
                case 'reference':
                    return model.getNodesWithProperty('scalarType', selector['content-type']);
            }

            return null;
        }

        /* Apply one component's modifiers. Only the two the built-in layouts use are
         * implemented; anything else returns null and aborts, for the same reason as above. */
        function lensApplyModifiers(nodes, modifiers) {
            if (!modifiers) return nodes;

            for (var i = 0; i < modifiers.length; i++) {
                var mod = modifiers[i];

                if (mod.type === 'sort') {
                    nodes = lensSort(nodes, mod);
                    continue;
                }

                if (mod.type !== 'filter' || mod.subtype !== 'relationship') return null;

                /* The server's relationship filter *adds* related content to the selection
                 * rather than narrowing it (Lens_model pushes onto $my_contents as it walks
                 * it). It walks the original members only — PHP's foreach iterates a copy —
                 * so this expands one level, as that does.
                 *
                 * 'child' means relations where the node is the body, which is scalarapi's
                 * 'outgoing'; 'parent' is 'incoming'. A content-types list of ['all-types']
                 * means every relation kind, which getRelatedNodes() spells as a null type. */
                var direction = mod.relationship === 'parent' ? 'incoming'
                              : mod.relationship === 'child'  ? 'outgoing'
                              : 'both';
                var types = mod['content-types'];
                if (!types || !types.length || types[0] === 'all-types') types = [null];

                var expanded = nodes.concat();
                for (var j = 0; j < nodes.length; j++) {
                    for (var t = 0; t < types.length; t++) {
                        expanded = expanded.concat(nodes[j].getRelatedNodes(types[t], direction));
                    }
                }
                nodes = expanded;
            }

            return nodes;
        }

        function lensSort(nodes, sort) {
            var descending = sort['sort-order'] === 'descending';
            var sorted     = nodes.concat();

            if (sort['sort-type'] === 'alphabetical') {
                sorted.sort(function (a, b) {
                    var x = (a.getSortTitle() || '').toLowerCase();
                    var y = (b.getSortTitle() || '').toLowerCase();
                    return x < y ? -1 : (x > y ? 1 : 0);
                });
            } else if (sort['sort-type'] === 'creation-date') {
                sorted.sort(function (a, b) {
                    return String(a.created || '').localeCompare(String(b.created || ''));
                });
            } else {
                // relation-type, num-relations, string-matches and visit-date are all sorts the
                // server computes from columns it adds to the response; leave the order alone
                // rather than inventing one.
                return nodes;
            }

            return descending ? sorted.reverse() : sorted;
        }

        /* Resolve a lens against the local model, returning it with 'items' filled in — the
         * same envelope POST <approot>/lenses returns on a live server.
         *
         * base.filter()'s "lens" branch uses items purely as a set of node URLs to look up in
         * scalarapi.model, and takes relationships from the model rather than from the payload,
         * so the entries only have to be faithful enough for parsePagesByType() to re-parse
         * without damage. nodeEntries() builds them from the same RDFa the nodes came from, so
         * that re-parse is a no-op.
         *
         * Multiple components are unioned. The live model picks the set operation from the
         * visualization type (Lens_model::get_operation_from_visualization) — every built-in
         * layout has exactly one component, so there is nothing to combine. */
        function resolveLens(lens) {
            var components = lens.components || [];
            var selected   = [];

            for (var i = 0; i < components.length; i++) {
                var nodes = lensSelectNodes(components[i]['content-selector']);
                if (nodes === null) return null;
                nodes = lensApplyModifiers(nodes, components[i].modifiers);
                if (nodes === null) return null;
                selected = selected.concat(nodes);
            }

            // Sorts declared on the lens itself, which the visualization's sort control writes
            // (see base.updateSorts) and the server applies after the components are combined.
            if (lens.sorts) {
                for (var s = 0; s < lens.sorts.length; s++) selected = lensSort(selected, lens.sorts[s]);
            }

            var resolved = {};
            for (var key in lens) resolved[key] = lens[key];
            resolved.items = nodeEntries(selected);

            return resolved;
        }

        window.__scalarStaticEndpoint = function (method, url, body) {

            var path = url.split('?')[0].split('#')[0].replace(/\/+$/, '');

            /* POST <approot>/lenses — resolve a lens. This is what every lens-driven
             * visualization runs on: the 'vis', 'visindex', 'vistoc', 'visconnections',
             * 'visradial', 'vispath', 'vismedia' and 'vistag' layouts, the header's
             * visualization menu, inline [vis] widgets and search results all build a lens
             * client-side and POST it here to be resolved. Left to the 503 they showed their
             * chrome and never received any data. */
            if (method === 'POST' && path.slice(-7) === '/lenses') {
                var lens;
                try {
                    lens = JSON.parse(typeof body === 'string' ? body : String(body));
                } catch (e) {
                    return null;
                }
                var resolved = resolveLens(lens);
                if (resolved === null) {
                    if (window.console) {
                        console.log('static export: this lens uses a selector or modifier the ' +
                                    'export cannot resolve locally; no items returned.', lens);
                    }
                    return null;
                }
                return JSON.stringify(resolved);
            }

            /* GET <approot>/lenses?book_id=N — the book's saved lenses, which populate the
             * header's visualization menu below its built-in entries. Editorial state is not
             * exported (see CLAUDE.md), so there are none; an empty array is what the live API
             * returns for a book that has none, and handleLensData() renders the menu without
             * them. */
            if (method === 'GET' && path.slice(-7) === '/lenses') return '[]';

            /* GET <approot>/ontologies — the metadata-field vocabulary behind search's field
             * menu. The live endpoint serves a config array from the server install; rather
             * than bake a copy that can drift, return the empty envelope its handler expects.
             * ScalarSearch.handleOntologyData() then adds dcterms:title, dcterms:description,
             * sioc:content, rdf:type and the scalar: fields itself, so the menu still offers
             * everything the built-in fields cover — just not any custom namespaces the
             * original install had configured. It indexes straight into .dcterms, so this
             * cannot be '{}'. */
            if (method === 'GET' && path.slice(-11) === '/ontologies') return '{"dcterms":[]}';

            return null;
        };

        /* Main menu "Home" link and Table of Contents fixes.
         *
         * scalarheader.jquery.js builds the Table of Contents dropdown's Home item from
         * scalarapi.model.parent_uri — the live book URL carried in <link id="parent">,
         * which page.php has to keep intact because it doubles as the RDF resource
         * namespace scalarapi resolves every node identifier against. So the link is
         * correct as RDF and wrong as navigation: clicking it leaves the export for the
         * original Scalar site. Repoint it at the export's own root index.html.
         *
         * The mobile "Home Page" link and the navbar book title don't need patching here
         * — both derive from #book-title's href, which page.php already emits as a
         * root-relative index.html.
         *
         * The Table of Contents itself — the author-curated page list below Home — needs
         * no data work: scalarheader builds it from the scalar:Page node at <book_url>toc,
         * whose dcterms:references list page.php emits as RDFa on every exported page, so
         * the list already populates. What doesn't survive the move off a live server is
         * everything the list links to:
         *
         *   - The TOC entries, and the "Visit page" and relationship links in the panel
         *     that slides out from an entry's arrow, are all built from ScalarNode.url and
         *     so point back at the original Scalar site. rewriteNodeLinks() repoints them
         *     at the export's own directories.
         *
         *   - That slide-out panel is filled by expandMenu() from a scalarapi.loadPage()
         *     success callback — one of the callback-only callers the loadNode()/loadPage()
         *     patch above now serves, so it fills itself and the links it builds are
         *     repointed by the MutationObserver when they land.
         *
         * Like the colophon fix above, this runs on the already-built DOM: base.init() is
         * called from $.scalarheader's constructor body, so the header is fully rendered
         * by the time $.fn.scalarheader returns. */
        if ($.fn.scalarheader) {
            var _originalScalarheader = $.fn.scalarheader;
            $.fn.scalarheader = function (options) {
                var header = _originalScalarheader.call(this, options);

                rewriteNodeLinks(header.$el);

                var homeLink = $('#scalarheader .home_link a')[0];
                if (homeLink) {
                    // applyCurrentQueryVarsToURL() may have appended ?path=/&m= state that
                    // should survive; only the book-URL half of the href is being replaced.
                    var href  = homeLink.getAttribute('href') || '';
                    var q     = href.indexOf('?');
                    var query = q === -1 ? '' : href.slice(q);
                    homeLink.setAttribute('href', exportRoot() + 'index.html' + query);
                }

                return header;
            };
        }

    });

}(window.jQuery));

