/* scalar-static-maps.js
 * A keyless stand-in for the parts of the Google Maps JavaScript API that Scalar uses, drawn
 * with Leaflet. Loaded by scalar-static-bridge.js in place of the real API when
 * scalar-static-config.js has no Google Maps key.
 * Auto-generated by the static exporter — do not edit manually.
 */
/*
 * Why a stand-in rather than a Leaflet version of each map feature: Scalar's four map features
 * (the Google Map layout and marker helper in scalarpage.jquery.js, the map widget in
 * scalarwidgets.jquery.js, MapVisualization in scalarvisualizations.jquery.js, and KML media in
 * jquery.mediaelement.js) share one small slice of the API, so answering that slice lets all
 * four run unmodified — and lets a book switch to the real API by adding a key, with nothing
 * else changing. The slice:
 *
 *   Map, Marker, InfoWindow, LatLng, LatLngBounds, Size, Point, Polyline, KmlLayer,
 *   MapTypeId, event.addListener, and OverlappingMarkerSpiderfier (the Google plugin the
 *   visualization uses; here an adapter over its Leaflet port).
 *
 * Beyond the documented API, Scalar also relies on a few of Google's MVCObject habits, which
 * are reproduced deliberately:
 *
 *   - Options become properties. Scalar passes its own 'html' option to Marker and reads it
 *     back as marker.html in click listeners.
 *   - marker.position is readable directly (the map widget extends its bounds with it).
 *   - Listeners run with `this` set to the object they were added to.
 *   - A map's 'idle' event fires after it settles, including after a fitBounds() call that
 *     happened before the listener was added (the visualization adds its listener right after).
 *
 * KML is not supported: KmlLayer only shows the bridge's notice on a KML media item.
 */
(function (window, L) {
    'use strict';

    if (!L) return;
    if (window.google && window.google.maps && window.google.maps.__scalarStaticStandIn) return;

    var bridge     = window.__scalarStaticMaps || {};
    var LeafletOMS = window.OverlappingMarkerSpiderfier;   // oms-leaflet.js, loaded just before this

    function tileSettings() {
        return (bridge.config ? bridge.config() : {}).tiles || {
            url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            maxZoom: 19,
            subdomains: 'abc'
        };
    }

    /* ---- Events --------------------------------------------------------------------------- */

    /* Mixed into every class below. Listeners are called with `this` bound to the object, and
     * addListener() returns a handle with remove(), both as Google's do. */
    var Evented = {
        addListener: function (name, fn) {
            var all  = this.__listeners || (this.__listeners = {}),
                list = all[name] || (all[name] = []);
            list.push(fn);
            return {
                remove: function () {
                    var i = list.indexOf(fn);
                    if (i !== -1) list.splice(i, 1);
                }
            };
        },
        __trigger: function (name, args) {
            var list = this.__listeners && this.__listeners[name];
            if (!list) return;
            list = list.slice();
            for (var i = 0; i < list.length; i++) list[i].apply(this, args || []);
        }
    };

    function evented(Class) {
        Class.prototype.addListener = Evented.addListener;
        Class.prototype.__trigger   = Evented.__trigger;
        return Class;
    }

    var event = {
        addListener: function (obj, name, fn) {
            return obj && typeof obj.addListener === 'function'
                ? obj.addListener(name, fn) : { remove: function () {} };
        },
        addListenerOnce: function (obj, name, fn) {
            var handle = event.addListener(obj, name, function () {
                handle.remove();
                return fn.apply(this, arguments);
            });
            return handle;
        },
        removeListener: function (handle) {
            if (handle && typeof handle.remove === 'function') handle.remove();
        },
        clearListeners: function (obj, name) {
            if (obj && obj.__listeners) delete obj.__listeners[name];
        },
        clearInstanceListeners: function (obj) {
            if (obj) obj.__listeners = {};
        },
        trigger: function (obj, name) {
            if (obj && typeof obj.__trigger === 'function') {
                obj.__trigger(name, Array.prototype.slice.call(arguments, 2));
            }
        }
    };

    /* ---- Geometry ------------------------------------------------------------------------- */

    /* Google clamps latitude to ±90 and wraps longitude into [-180, 180] unless told not to. */
    function LatLng(lat, lng, noClampNoWrap) {
        if (lat && typeof lat === 'object') {
            noClampNoWrap = lng;
            lng = typeof lat.lng === 'function' ? lat.lng() : lat.lng;
            lat = typeof lat.lat === 'function' ? lat.lat() : lat.lat;
        }
        lat = Number(lat);
        lng = Number(lng);
        if (!noClampNoWrap) {
            lat = Math.max(-90, Math.min(90, lat));
            if (isFinite(lng) && (lng < -180 || lng > 180)) lng = ((lng + 180) % 360 + 360) % 360 - 180;
        }
        this.__lat = lat;
        this.__lng = lng;
    }
    LatLng.prototype.lat = function () { return this.__lat; };
    LatLng.prototype.lng = function () { return this.__lng; };
    LatLng.prototype.toJSON = function () { return { lat: this.__lat, lng: this.__lng }; };
    LatLng.prototype.toString = function () { return '(' + this.__lat + ', ' + this.__lng + ')'; };
    LatLng.prototype.toUrlValue = function (precision) {
        var p = Math.pow(10, precision === undefined ? 6 : precision);
        return Math.round(this.__lat * p) / p + ',' + Math.round(this.__lng * p) / p;
    };
    LatLng.prototype.equals = function (other) {
        return !!other && other.lat() === this.__lat && other.lng() === this.__lng;
    };

    function asLatLng(value) {
        return value instanceof LatLng ? value : new LatLng(value);
    }

    /* A LatLng, LatLngLiteral or Leaflet LatLng as a Leaflet LatLng, or null if it isn't a
     * usable coordinate — Leaflet throws on NaN where Google would quietly ignore it. */
    function toLeaflet(value) {
        if (!value) return null;
        var lat = typeof value.lat === 'function' ? value.lat() : value.lat,
            lng = typeof value.lng === 'function' ? value.lng() : value.lng;
        lat = Number(lat);
        lng = Number(lng);
        return (isFinite(lat) && isFinite(lng)) ? L.latLng(lat, lng) : null;
    }

    function fromLeaflet(ll) {
        return new LatLng(ll.lat, ll.lng, true);
    }

    function LatLngBounds(sw, ne) {
        this.__bounds = null;
        if (sw) this.extend(sw);
        if (ne) this.extend(ne);
    }
    LatLngBounds.prototype.extend = function (point) {
        var ll = toLeaflet(point);
        if (!ll) return this;
        if (this.__bounds) this.__bounds.extend(ll);
        else this.__bounds = L.latLngBounds(ll, ll);
        return this;
    };
    LatLngBounds.prototype.union = function (other) {
        if (other && other.__bounds) {
            this.extend(other.__bounds.getSouthWest());
            this.extend(other.__bounds.getNorthEast());
        }
        return this;
    };
    LatLngBounds.prototype.isEmpty = function () { return !this.__bounds; };
    LatLngBounds.prototype.contains = function (point) {
        var ll = toLeaflet(point);
        return !!(this.__bounds && ll && this.__bounds.contains(ll));
    };
    LatLngBounds.prototype.getCenter = function () {
        return this.__bounds ? fromLeaflet(this.__bounds.getCenter()) : new LatLng(0, 0);
    };
    LatLngBounds.prototype.getNorthEast = function () {
        return this.__bounds ? fromLeaflet(this.__bounds.getNorthEast()) : new LatLng(-90, -180);
    };
    LatLngBounds.prototype.getSouthWest = function () {
        return this.__bounds ? fromLeaflet(this.__bounds.getSouthWest()) : new LatLng(90, 180);
    };
    LatLngBounds.prototype.toJSON = function () {
        if (!this.__bounds) return { north: -90, east: -180, south: 90, west: 180 };
        return {
            north: this.__bounds.getNorth(), east: this.__bounds.getEast(),
            south: this.__bounds.getSouth(), west: this.__bounds.getWest()
        };
    };

    function Size(width, height) {
        this.width = width;
        this.height = height;
    }

    function Point(x, y) {
        this.x = x;
        this.y = y;
    }

    var MapTypeId = { HYBRID: 'hybrid', ROADMAP: 'roadmap', SATELLITE: 'satellite', TERRAIN: 'terrain' };

    /* Great-circle arc from a to b as a run of points about a degree apart, for
     * Polyline({geodesic: true}) — which is how the visualization draws the route between the
     * stops of a path. Longitudes are kept continuous across the antimeridian, so a route over
     * the Pacific goes the short way instead of across the whole map. */
    function greatCircle(points) {
        var rad = Math.PI / 180, out = [], i, j;

        for (i = 0; i < points.length; i++) {
            if (i === 0) { out.push(points[0]); continue; }

            var a = points[i - 1], b = points[i],
                lat1 = a.lat * rad, lon1 = a.lng * rad,
                lat2 = b.lat * rad, lon2 = b.lng * rad,
                d = 2 * Math.asin(Math.sqrt(
                    Math.pow(Math.sin((lat2 - lat1) / 2), 2) +
                    Math.cos(lat1) * Math.cos(lat2) * Math.pow(Math.sin((lon2 - lon1) / 2), 2)));

            // Coincident or antipodal: no single great circle to follow.
            if (d < 1e-9 || Math.abs(Math.sin(d)) < 1e-9) { out.push(b); continue; }

            var steps = Math.max(1, Math.min(180, Math.ceil(d / rad)));
            for (j = 1; j <= steps; j++) {
                var f  = j / steps,
                    A  = Math.sin((1 - f) * d) / Math.sin(d),
                    B  = Math.sin(f * d) / Math.sin(d),
                    x  = A * Math.cos(lat1) * Math.cos(lon1) + B * Math.cos(lat2) * Math.cos(lon2),
                    y  = A * Math.cos(lat1) * Math.sin(lon1) + B * Math.cos(lat2) * Math.sin(lon2),
                    z  = A * Math.sin(lat1) + B * Math.sin(lat2);
                out.push(L.latLng(Math.atan2(z, Math.sqrt(x * x + y * y)) / rad, Math.atan2(y, x) / rad));
            }
        }

        for (i = 1; i < out.length; i++) {
            var lng = out[i].lng;
            while (lng - out[i - 1].lng > 180) lng -= 360;
            while (lng - out[i - 1].lng < -180) lng += 360;
            if (lng !== out[i].lng) out[i] = L.latLng(out[i].lat, lng);
        }

        return out;
    }

    /* ---- Map ------------------------------------------------------------------------------ */

    /* The tile layer comes from scalar-static-config.js (see the bridge's config()). Two
     * behaviours of Google's embedded maps are matched because readers would notice their
     * absence:
     *
     *   - A map created without a center shows nothing until something centres it, and the
     *     zoom it was created with applies then. Leaflet can't exist without a view, so the map
     *     starts on the whole world and the first setCenter() applies the requested zoom.
     *   - Scrolling the page over a map scrolls the page; zooming with the wheel needs Ctrl or
     *     ⌘, as with Google's default gesture handling on a scrollable page. */
    function GoogleMap(div, opts) {
        opts = opts || {};

        var self  = this,
            tiles = tileSettings();

        /* Scalar builds a visualization on an element that may already hold one: the modal
         * drops its instance when it closes and builds a new one on reopen, and its type
         * selector does the same. Google replaces whatever was in the element; Leaflet throws
         * "Map container is already initialized", so the old map is torn down first. */
        if (div.__scalarStaticMap) div.__scalarStaticMap.__teardown();

        this.__div = div;
        div.__scalarStaticMap = this;
        this.__inlinePosition = div.style.position;   // Leaflet overwrites this; see __teardown()
        this.__centered = false;
        this.__initialZoom = typeof opts.zoom === 'number' ? opts.zoom : null;
        this.__mapTypeId = opts.mapTypeId || MapTypeId.ROADMAP;

        this.__map = L.map(div, {
            worldCopyJump: true,
            maxZoom: tiles.maxZoom,
            minZoom: typeof opts.minZoom === 'number' ? opts.minZoom : 0
        });

        L.tileLayer(tiles.url, {
            attribution: tiles.attribution,
            maxZoom: tiles.maxZoom,
            subdomains: tiles.subdomains
        }).addTo(this.__map);

        if (opts.center && toLeaflet(opts.center)) {
            this.__map.setView(toLeaflet(opts.center), this.__initialZoom !== null ? this.__initialZoom : 2);
            this.__centered = true;
        } else {
            this.__map.setView([20, 0], 1);
        }

        div.addEventListener('wheel', function (e) {
            if (!e.ctrlKey && !e.metaKey) e.stopImmediatePropagation();
        }, true);

        // Google redraws when its element changes size; Leaflet has to be told.
        this.__pendingFit = null;
        var resized = function () {
            self.__map.invalidateSize();
            self.__applyPendingFit();
        };
        if (typeof ResizeObserver === 'function') {
            this.__observer = new ResizeObserver(resized);
            this.__observer.observe(div);
        } else {
            this.__resizeHandler = resized;
            window.addEventListener('resize', resized);
        }

        /* Scalar's visualizations share one element: switching type empties it and draws
         * something else there, without telling the map. Leaflet's classes would stay behind —
         * one of them paints the grey map background — and this map would go on watching an
         * element it no longer owns. Leaflet's panes being pulled out is the signal that it has
         * happened. */
        if (typeof MutationObserver === 'function') {
            this.__domObserver = new MutationObserver(function () {
                var pane = self.__map && self.__map._mapPane;
                if (pane && !div.contains(pane)) self.__teardown();
            });
            this.__domObserver.observe(div, { childList: true });
        }

        var idleTimer = null;
        this.__map.on('moveend', function () {
            self.__trigger('center_changed');
            self.__trigger('bounds_changed');
            clearTimeout(idleTimer);
            idleTimer = setTimeout(function () { self.__trigger('idle'); }, 0);
        });
        this.__map.on('zoomend', function () { self.__trigger('zoom_changed'); });
        this.__map.on('click', function (e) {
            self.__trigger('click', [{ latLng: fromLeaflet(e.latlng) }]);
        });

        setTimeout(function () { self.__trigger('idle'); }, 0);
    }
    evented(GoogleMap);

    /* Give up the element: stop watching it for resizes — the watcher would otherwise go on
     * poking a map that is no longer on the page — and let Leaflet release it so another map
     * can be built there. If Leaflet won't (it refuses when it thinks another instance holds
     * the element), clear its claim by hand, since the element is being reused regardless. */
    GoogleMap.prototype.__teardown = function () {
        if (this.__observer) {
            try { this.__observer.disconnect(); } catch (e) { /* already gone */ }
            this.__observer = null;
        }
        if (this.__domObserver) {
            try { this.__domObserver.disconnect(); } catch (e) { /* already gone */ }
            this.__domObserver = null;
        }
        if (this.__resizeHandler) {
            window.removeEventListener('resize', this.__resizeHandler);
            this.__resizeHandler = null;
        }
        try {
            this.__map.remove();
        } catch (e) {
            try { delete this.__div._leaflet_id; } catch (e2) { /* nothing more to try */ }
        }
        /* Leaflet leaves its own classes on the element and sets position:relative on it.
         * Both have to go: .leaflet-container paints a grey background, which would sit behind
         * whatever Scalar draws on this element next. */
        var div = this.__div, classes, kept = [], i;
        if (div) {
            classes = (div.className || '').split(/\s+/);
            for (i = 0; i < classes.length; i++) {
                if (classes[i] && classes[i].indexOf('leaflet-') !== 0) kept.push(classes[i]);
            }
            div.className = kept.join(' ');
            div.style.position = this.__inlinePosition || '';
            if (div.__scalarStaticMap === this) div.__scalarStaticMap = null;
        }
    };

    GoogleMap.prototype.getDiv = function () { return this.__div; };

    GoogleMap.prototype.setCenter = function (latlng) {
        var ll = toLeaflet(latlng);
        if (!ll) return;
        this.__syncSize();
        var zoom = (!this.__centered && this.__initialZoom !== null) ? this.__initialZoom : this.__map.getZoom();
        this.__map.setView(ll, zoom, { animate: false });
        this.__centered = true;
    };
    GoogleMap.prototype.panTo = function (latlng) {
        var ll = toLeaflet(latlng);
        if (ll) this.__map.panTo(ll);
        this.__centered = true;
    };
    GoogleMap.prototype.getCenter = function () { return fromLeaflet(this.__map.getCenter()); };
    GoogleMap.prototype.setZoom = function (zoom) {
        if (typeof zoom === 'number' && isFinite(zoom)) this.__map.setZoom(zoom, { animate: false });
    };
    GoogleMap.prototype.getZoom = function () { return this.__map.getZoom(); };
    GoogleMap.prototype.getBounds = function () {
        var b = this.__map.getBounds();
        return new LatLngBounds(fromLeaflet(b.getSouthWest()), fromLeaflet(b.getNorthEast()));
    };

    /* Leaflet measures its element once and re-measures only on a window resize or an explicit
     * invalidateSize(); Google measures on every draw. That difference matters because Scalar
     * builds a modal visualization while the modal is still hidden and draws it again when the
     * modal opens (see the 'shown.bs.modal' handler in scalarvisualizations.jquery.js): without
     * this, both draws use the size the element had while hidden — zero — and the map ends up at
     * maximum zoom on an empty patch of the world. Returns whether the element has a size now. */
    GoogleMap.prototype.__syncSize = function () {
        var div = this.__div, size = this.__map.getSize();
        if (div.clientWidth !== size.x || div.clientHeight !== size.y) {
            this.__map.invalidateSize({ animate: false, pan: false });
        }
        return div.clientWidth > 0 && div.clientHeight > 0;
    };

    // A fit asked for while the element had no size, applied once it has one.
    GoogleMap.prototype.__applyPendingFit = function () {
        var pending = this.__pendingFit;
        if (!pending || this.__div.clientWidth <= 0 || this.__div.clientHeight <= 0) return;
        this.__pendingFit = null;
        this.fitBounds(pending.bounds, pending.padding);
    };

    /* An empty bounds is ignored, as Google's is. A single point zooms all the way in, as
     * Google's does — the visualization calls this even when there's one marker. */
    GoogleMap.prototype.fitBounds = function (bounds, padding) {
        if (!bounds || !bounds.__bounds) return;
        var pad = typeof padding === 'number' ? padding : 40;

        if (!this.__syncSize()) {
            // Hidden, or not laid out yet. Remember the request for when it has a size.
            this.__pendingFit = { bounds: bounds, padding: pad };
            this.__centered = true;
            return;
        }
        this.__pendingFit = null;

        // Padding wider than the element itself leaves Leaflet a negative viewport to fit into,
        // whose zoom works out as NaN. Never take more than a quarter of the smaller side.
        var size = this.__map.getSize();
        pad = Math.max(0, Math.min(pad, Math.floor(Math.min(size.x, size.y) / 4)));

        this.__map.fitBounds(bounds.__bounds, { padding: [pad, pad], animate: false });
        this.__centered = true;
    };

    GoogleMap.prototype.setOptions = function (opts) {
        if (!opts) return;
        if (opts.center) this.setCenter(opts.center);
        if (typeof opts.zoom === 'number') this.setZoom(opts.zoom);
        if (opts.mapTypeId) this.__mapTypeId = opts.mapTypeId;
    };
    // Only road maps are available without Google.
    GoogleMap.prototype.setMapTypeId = function (id) { this.__mapTypeId = id; };
    GoogleMap.prototype.getMapTypeId = function () { return this.__mapTypeId; };

    /* ---- Overlays ------------------------------------------------------------------------- */

    /* Adds or removes a Leaflet layer to follow setMap(), for Marker and Polyline. */
    function setLayerMap(overlay, layer, map) {
        if (overlay.map && overlay.map.__map) overlay.map.__map.removeLayer(layer);
        overlay.map = map || null;
        if (overlay.map && overlay.map.__map) layer.addTo(overlay.map.__map);
    }

    function Marker(opts) {
        opts = opts || {};
        var self = this, key;

        // Options become properties, as on Google's MVCObject — Scalar reads its own 'html'.
        for (key in opts) {
            if (Object.prototype.hasOwnProperty.call(opts, key) &&
                key !== 'map' && key !== 'position' && key !== 'icon') {
                this[key] = opts[key];
            }
        }

        this.map = null;
        this.position = null;
        this.__marker = L.marker([0, 0], {
            title: opts.title || '',
            alt: opts.title || '',
            riseOnHover: true
        });
        this.__marker.__scalarStandIn = this;
        this.__marker.on('click', function () {
            self.__trigger('click', [{ latLng: self.position }]);
        });

        if (opts.icon) this.setIcon(opts.icon);
        if (opts.position) this.setPosition(opts.position);
        if (opts.map) this.setMap(opts.map);
    }
    evented(Marker);

    Marker.prototype.setPosition = function (position) {
        this.position = asLatLng(position);
        var ll = toLeaflet(this.position);
        if (ll) this.__marker.setLatLng(ll);
    };
    Marker.prototype.getPosition = function () { return this.position; };
    Marker.prototype.setMap = function (map) { setLayerMap(this, this.__marker, map); };
    Marker.prototype.getMap = function () { return this.map; };
    Marker.prototype.setTitle = function (title) {
        this.title = title;
        var el = this.__marker.getElement();
        if (el) el.title = title || '';
        this.__marker.options.title = title || '';
    };
    Marker.prototype.getTitle = function () { return this.title; };
    Marker.prototype.setVisible = function (visible) {
        this.__marker.setOpacity(visible === false ? 0 : 1);
    };
    Marker.prototype.setZIndex = function (z) { this.__marker.setZIndexOffset(z || 0); };

    /* A URL, or an Icon object with url, scaledSize and anchor. Google anchors an icon at its
     * bottom centre unless told otherwise. */
    Marker.prototype.setIcon = function (icon) {
        this.icon = icon;

        /* No icon, or one whose url isn't ready: Leaflet throws where Google quietly draws its
         * default pin. The map visualization relies on that — it builds its marker images from
         * SVG through an Image.onload (MapVisualization.generateIcon), so every draw that
         * happens before those land asks for an icon with no url. */
        var url = (typeof icon === 'string') ? icon : (icon && icon.url);
        if (!url) {
            this.__marker.setIcon(new L.Icon.Default());
            return;
        }

        var size = (typeof icon === 'object' && (icon.scaledSize || icon.size)) || null,
            options = { iconUrl: url };

        if (size) {
            options.iconSize = [size.width, size.height];
            options.iconAnchor = (icon.anchor ? [icon.anchor.x, icon.anchor.y] : [size.width / 2, size.height]);
            options.popupAnchor = [0, -options.iconAnchor[1]];
        }
        this.__marker.setIcon(L.icon(options));
    };

    /* Leaflet closes one popup when another opens, where Google lets several InfoWindows stay
     * open. Scalar only ever wants one, so the difference doesn't show. */
    function InfoWindow(opts) {
        opts = opts || {};
        this.map = null;
        this.__content = opts.content || '';
        this.__position = opts.position ? asLatLng(opts.position) : null;
        this.__popup = L.popup({ maxWidth: opts.maxWidth || 300, autoPanPadding: [20, 20] });
    }
    evented(InfoWindow);

    InfoWindow.prototype.setContent = function (content) { this.__content = content; };
    InfoWindow.prototype.getContent = function () { return this.__content; };
    InfoWindow.prototype.setPosition = function (position) { this.__position = asLatLng(position); };
    InfoWindow.prototype.getPosition = function () { return this.__position; };

    /* open(map, anchor) or open({map, anchor}), with the window placed over the anchor's icon. */
    InfoWindow.prototype.open = function (map, anchor) {
        if (map && !(map instanceof GoogleMap) && (map.map || map.anchor)) {
            anchor = map.anchor;
            map = map.map;
        }
        if (!map && anchor && anchor.getMap) map = anchor.getMap();
        if (!map || !map.__map) return;

        var ll = toLeaflet(anchor && anchor.getPosition ? anchor.getPosition() : this.__position);
        if (!ll) return;

        var popupAnchorY = -41;   // Leaflet's default marker
        if (anchor && anchor.__marker) {
            var iconOptions = anchor.__marker.options.icon && anchor.__marker.options.icon.options;
            if (iconOptions && iconOptions.popupAnchor) popupAnchorY = iconOptions.popupAnchor[1];
        } else if (!anchor) {
            popupAnchorY = 0;
        }
        this.__popup.options.offset = L.point(0, 7 + popupAnchorY);

        this.__popup.setLatLng(ll).setContent(this.__content);
        this.__popup.openOn(map.__map);
        this.map = map;
    };
    InfoWindow.prototype.close = function () {
        if (this.map && this.map.__map) this.map.__map.closePopup(this.__popup);
        this.map = null;
    };

    function Polyline(opts) {
        opts = opts || {};
        this.map = null;
        this.__geodesic = !!opts.geodesic;
        this.__path = [];
        // strokeColor may be a d3 color object (the visualization passes d3.rgb(…)).
        this.__line = L.polyline([], {
            color:   opts.strokeColor != null ? String(opts.strokeColor) : '#000000',
            opacity: opts.strokeOpacity != null ? opts.strokeOpacity : 1,
            weight:  opts.strokeWeight != null ? opts.strokeWeight : 3,
            interactive: false
        });
        this.setPath(opts.path || []);
        if (opts.map) this.setMap(opts.map);
    }
    evented(Polyline);

    Polyline.prototype.setPath = function (path) {
        var points = [], i, ll;
        this.__path = [];
        path = (path && typeof path.getArray === 'function') ? path.getArray() : (path || []);
        for (i = 0; i < path.length; i++) {
            ll = toLeaflet(path[i]);
            if (!ll) continue;
            this.__path.push(asLatLng(path[i]));
            points.push(ll);
        }
        this.__line.setLatLngs(this.__geodesic ? greatCircle(points) : points);
    };
    Polyline.prototype.getPath = function () {
        var path = this.__path;
        return {
            getArray:  function () { return path.slice(); },
            getLength: function () { return path.length; },
            getAt:     function (i) { return path[i]; }
        };
    };
    Polyline.prototype.setMap = function (map) { setLayerMap(this, this.__line, map); };
    Polyline.prototype.getMap = function () { return this.map; };

    /* KML isn't drawn without Google. On a KML media item the bridge puts a notice in the
     * map's place; on a Google Map layout page the layer is simply left off, and the
     * defaultviewport_changed event that page waits for never fires. */
    function KmlLayer(opts) {
        this.map = null;
        this.url = typeof opts === 'string' ? opts : ((opts && opts.url) || '');
        if (opts && typeof opts === 'object' && opts.map) this.setMap(opts.map);
    }
    evented(KmlLayer);

    KmlLayer.prototype.setMap = function (map) {
        this.map = map || null;
        if (map && map.__div && bridge.kmlUnavailable) {
            bridge.kmlUnavailable(map.__div, this.url, 'no-key');
        }
    };
    KmlLayer.prototype.getMap = function () { return this.map; };
    KmlLayer.prototype.getUrl = function () { return this.url; };
    KmlLayer.prototype.getDefaultViewport = function () { return null; };
    KmlLayer.prototype.getStatus = function () { return 'UNKNOWN'; };

    /* ---- OverlappingMarkerSpiderfier ------------------------------------------------------ */

    /* The Google plugin's API over its Leaflet port. What the visualization needs:
     *
     *   - addMarker() also puts the marker on the map, as the Google plugin's does.
     *   - A click on a marker that needs no spiderfying — or on a leg of one that has been —
     *     fires 'spider_click' on the marker itself (the Google plugin's basicFormatEvents).
     *     The marker's own 'click' fires as well, as on Google.
     *   - legColors.usual / .highlighted are keyed by map type on Google and are single
     *     colours on Leaflet; the road map's entry is used. */
    function Spiderfier(map, opts) {
        opts = opts || {};
        var self = this, leafletOpts = {}, key;

        this.map = map;
        this.legColors = { usual: {}, highlighted: {} };

        var passThrough = ['keepSpiderfied', 'nearbyDistance', 'circleSpiralSwitchover',
                           'circleFootSeparation', 'spiralFootSeparation', 'legWeight'];
        for (var i = 0; i < passThrough.length; i++) {
            key = passThrough[i];
            if (Object.prototype.hasOwnProperty.call(opts, key)) leafletOpts[key] = opts[key];
        }

        this.__oms = new LeafletOMS(map.__map, leafletOpts);

        this.__oms.addListener('click', function (leafletMarker) {
            var marker = leafletMarker.__scalarStandIn;
            if (!marker) return;
            marker.__trigger('spider_click', [{ latLng: marker.position }]);
            self.__trigger('click', [marker]);
        });
        this.__oms.addListener('spiderfy', function (markers, others) {
            self.__trigger('spiderfy', [standIns(markers), standIns(others)]);
        });
        this.__oms.addListener('unspiderfy', function (markers, others) {
            self.__trigger('unspiderfy', [standIns(markers), standIns(others)]);
        });
    }
    evented(Spiderfier);

    function standIns(leafletMarkers) {
        var out = [];
        for (var i = 0; i < (leafletMarkers || []).length; i++) {
            if (leafletMarkers[i].__scalarStandIn) out.push(leafletMarkers[i].__scalarStandIn);
        }
        return out;
    }

    function legColor(colors, fallback) {
        var value = colors && (colors[MapTypeId.ROADMAP] || colors[Object.keys(colors)[0]]);
        return value ? String(value) : fallback;
    }

    Spiderfier.prototype.addMarker = function (marker, spiderClickListener) {
        this.__oms.legColors = {
            usual:       legColor(this.legColors.usual, '#222'),
            highlighted: legColor(this.legColors.highlighted, '#f00')
        };
        marker.setMap(this.map);
        this.__oms.addMarker(marker.__marker);
        if (typeof spiderClickListener === 'function') marker.addListener('spider_click', spiderClickListener);
        return this;
    };
    Spiderfier.prototype.removeMarker = function (marker) {
        this.__oms.removeMarker(marker.__marker);
        marker.setMap(null);
        return this;
    };
    Spiderfier.prototype.forgetMarker = function (marker) {
        this.__oms.removeMarker(marker.__marker);
        return this;
    };
    Spiderfier.prototype.removeAllMarkers = function () {
        var markers = this.getMarkers();
        this.__oms.clearMarkers();
        for (var i = 0; i < markers.length; i++) markers[i].setMap(null);
        return this;
    };
    Spiderfier.prototype.forgetAllMarkers = function () {
        this.__oms.clearMarkers();
        return this;
    };
    Spiderfier.prototype.getMarkers = function () { return standIns(this.__oms.getMarkers()); };
    Spiderfier.prototype.unspiderfy = function () { this.__oms.unspiderfy(); return this; };

    /* ---- Install -------------------------------------------------------------------------- */

    window.google = window.google || {};
    window.google.maps = {
        __scalarStaticStandIn: true,
        Map: GoogleMap,
        Marker: Marker,
        InfoWindow: InfoWindow,
        LatLng: LatLng,
        LatLngBounds: LatLngBounds,
        Size: Size,
        Point: Point,
        Polyline: Polyline,
        KmlLayer: KmlLayer,
        MapTypeId: MapTypeId,
        Animation: { BOUNCE: 1, DROP: 2 },
        event: event
    };

    if (typeof LeafletOMS === 'function') window.OverlappingMarkerSpiderfier = Spiderfier;

}(window, window.L));
